"use client";

import { Info } from "lucide-react";
import { useRef, useState } from "react";

const BUBBLE_WIDTH = 288;
const MARGIN = 16;

// The ⓘ next to a cost line: click reveals the model and the estimate note.
// The bubble is position:fixed, measured from the icon and clamped to the
// viewport, so it fits wherever the icon sits.
export function CostInfo({ model }: { model: string }) {
  const buttonRef = useRef<HTMLButtonElement>(null);
  const [pos, setPos] = useState<{ left: number; top: number; width: number } | null>(null);
  const toggle = () => {
    const rect = buttonRef.current?.getBoundingClientRect();
    if (pos || !rect) return setPos(null);
    const width = Math.min(BUBBLE_WIDTH, window.innerWidth - MARGIN * 2);
    setPos({
      left: Math.min(Math.max(MARGIN, rect.left), window.innerWidth - width - MARGIN),
      top: rect.bottom + 6,
      width,
    });
  };
  return (
    <span className="relative inline-flex align-middle">
      <button
        ref={buttonRef}
        type="button"
        aria-label="About this cost"
        className="inline-flex items-center text-muted-foreground hover:text-foreground"
        onClick={toggle}
        onBlur={() => setPos(null)}
      >
        <Info className="size-3.5" />
      </button>
      {pos && (
        <span
          style={pos}
          className="fixed z-50 rounded-md border bg-popover px-3 py-2 text-left text-xs text-popover-foreground shadow-md"
        >
          Generated by <code className="break-all">{model}</code>. Cost is an estimate at
          OpenRouter's listed rates — your OpenRouter invoice is authoritative.
        </span>
      )}
    </span>
  );
}
