// The mini-example implementations import their UI primitives from here — the
// path the shadcn CLI writes into an app. Docs snippets are their source file
// verbatim, so the import a reader sees is the one their own app would have,
// and the point lands: an implementation wraps an ordinary React component.
// Whether that component was generated by shadcn, hand-written, or (as here)
// re-exported from the catalog makes no difference to the implementation.
export * from "@uicast/shadcn-catalog/ui/card";
