// The shared expression corpus. It lives outside the test files so the language
// suite and the parity suite run the SAME list through their different back
// ends — a copy in each would drift, and the whole point of the parity suite is
// that both back ends see identical input.

export const SCOPES = {
	root: {
		q: "wid",
		count: 3,
		user: { name: "Ada", email: "ada@example.com", tags: ["a", "b"] },
		products: [
			{ id: 1, name: "Widget", sku: "W-1", category: "Tools", stock: 12, price: 9.5 },
			{ id: 2, name: "Gadget", sku: "G-2", category: "Tools", stock: 40, price: 24 },
			{ id: 3, name: "Doohickey", sku: "D-3", category: "Parts", stock: 0, price: 3.25 },
		],
		nothing: null,
	},
};

export const CORPUS = [
	`1 + 2 * 3 - 4 / 2`,
	`2 ** 3 ** 2`,
	`7 % 3`,
	`-0 === 0`,
	`0.1 + 0.2`,
	`1 / 0`,
	`-1 / 0`,
	`NaN === NaN`,
	`typeof undefined`,
	`typeof null`,
	`typeof 1`,
	`typeof "s"`,
	`typeof true`,
	`typeof []`,
	`typeof ({})`,
	`"" + 1`,
	`1 + "1"`,
	`"3" * "4"`,
	`[] + 1`,
	`[1,2] + ""`,
	`null + 1`,
	`undefined === null`,
	`null == undefined`,
	`"" == 0`,
	`"0" == false`,
	`[] == false`,
	`1 < 2 === true`,
	`true && "a"`,
	`false && "a"`,
	`0 || "a"`,
	`"" ?? "a"`,
	`null ?? "a"`,
	`undefined ?? null ?? 3`,
	`(1 > 2) ? "y" : "n"`,
	`!!"x"`,
	`+"12"`,
	`-"12"`,
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`a${1}b${2}c`",
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`${null}|${undefined}|${0}`",
	`[1,2,3].map(n => n * 2)`,
	`[1,2,3].filter(n => n % 2 === 1)`,
	`[1,2,3].reduce((a, b) => a + b, 0)`,
	`[1,2,3].reduce((a, b) => a + b)`,
	`[3,1,2].toSorted()`,
	`[3,1,2].toSorted((a, b) => b - a)`,
	`[1,[2,[3]]].flat(2)`,
	`[1,2].flatMap(n => [n, n])`,
	`[1,2,3].find(n => n > 1)`,
	`[1,2,3].findIndex(n => n > 5)`,
	`[1,2,3].indexOf(2)`,
	`[1,2,3].includes(9)`,
	`[1,2,3].at(-1)`,
	`[1,2,3].join("|")`,
	`[null, undefined, 1].join("-")`,
	`[].join(",")`,
	`[1,2,3].some(n => n > 2)`,
	`[1,2,3].every(n => n > 0)`,
	`[...[1,2], ...[3]]`,
	`[..."abc"]`,
	`({ a: 1, ...{ b: 2 } })`,
	`({ ["a" + 1]: 2 })`,
	`Object.keys({ b: 1, a: 2 })`,
	`Object.values({ a: 1 })`,
	`Object.entries({ a: 1 })`,
	`Object.fromEntries([["a", 1], ["b", 2]])`,
	`Math.max(1, 2, 3)`,
	`Math.min()`,
	`Math.round(-2.5)`,
	`Math.abs(-3)`,
	`Math.trunc(-4.7)`,
	`Math.sign(-0)`,
	`JSON.stringify({ b: 1, a: [1, null] })`,
	`JSON.stringify("x")`,
	`JSON.parse("[1,2]")`,
	`Number("")`,
	`Number("x")`,
	`Number(null)`,
	`Number(undefined)`,
	`String(null)`,
	`String([1,2])`,
	`String({})`,
	`Boolean("")`,
	`parseInt("12px")`,
	`parseFloat("3.5rem")`,
	`isNaN("x")`,
	`isFinite("3")`,
	`(255).toString(2)`,
	`(1.005).toFixed(2)`,
	`(12345.6789).toFixed(0)`,
	`"Hello".toLowerCase()`,
	`"Hello".slice(1, 3)`,
	`"Hello".substring(3, 1)`,
	`"Hello".at(-1)`,
	`"a-b-c".split("-")`,
	`"a-b-c".split("-", 2)`,
	`"aaa".replace("a", "b")`,
	`"aaa".replaceAll("a", "b")`,
	`"x".repeat(3)`,
	`"5".padStart(3, "0")`,
	`"abc".indexOf("c")`,
	`"abc".includes("b")`,
	`"abc".startsWith("ab")`,
	`" a ".trim().length`,
	`encodeURIComponent("a b&c")`,
	`decodeURIComponent("a%20b")`,
	`new Date(0).toISOString()`,
	`new Date(0).getTime()`,
	`new Map([["a", 1]]).get("a")`,
	`new Set([1, 1]).size`,
	`new URL("https://x.example/a?b=1").pathname`,
	`Array.from({ length: 3 })`,
	`Array.isArray("x")`,
	`[{ a: 1 }, { a: 2 }].map(({ a }) => a)`,
	`[[1, 2], [3, 4]].map(([x, y]) => x * y)`,
	`[undefined].map((v = 5) => v)`,
	`[1,2,3].map((n, i, all) => n + i + all.length)`,
	`[1,2,3][-1]`,
	`[1,2,3][1.5]`,
	`"abc"[-1]`,
	`"e\u0301".normalize("NFC").length`,
	`({ toString: 1 }).toString`,
];
