// Shared by the corpus and parity suites, so both back ends see the same list.

export const SCOPES = {
	root: {
		q: "wid",
		count: 3,
		user: { name: "Ada", email: "ada@example.com", tags: ["a", "b"] },
		products: [
			{ id: 1, name: "Widget", sku: "W-1", category: "Tools", stock: 12, price: 9.5 },
			{ id: 2, name: "Gadget", sku: "G-2", category: "Tools", stock: 40, price: 24 },
			{ id: 3, name: "Doohickey", sku: "D-3", category: "Parts", stock: 0, price: 3.25 },
		],
		nothing: null,
	},
};

export const CORPUS = [
	`1 + 2 * 3 - 4 / 2`,
	`2 ** 3 ** 2`,
	`7 % 3`,
	`-0 === 0`,
	`0.1 + 0.2`,
	`1 / 0`,
	`-1 / 0`,
	`NaN === NaN`,
	`typeof undefined`,
	`typeof null`,
	`typeof 1`,
	`typeof "s"`,
	`typeof true`,
	`typeof []`,
	`typeof ({})`,
	`typeof Date`,
	`typeof Math`,
	`"" + 1`,
	`1 + "1"`,
	`"3" * "4"`,
	`[] + 1`,
	`[1,2] + ""`,
	`null + 1`,
	`undefined === null`,
	`null == undefined`,
	`"" == 0`,
	`"0" == false`,
	`[] == false`,
	`1 < 2 === true`,
	`true && "a"`,
	`false && "a"`,
	`0 || "a"`,
	`"" ?? "a"`,
	`null ?? "a"`,
	`undefined ?? null ?? 3`,
	`(1 > 2) ? "y" : "n"`,
	`!!"x"`,
	`+"12"`,
	`-"12"`,
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`a${1}b${2}c`",
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`${null}|${undefined}|${0}`",
	`[1,2,3].map(n => n * 2)`,
	`[1,2,3].filter(n => n % 2 === 1)`,
	`[1,2,3].reduce((a, b) => a + b, 0)`,
	`[1,2,3].reduce((a, b) => a + b)`,
	`[3,1,2].toSorted()`,
	`[3,1,2].toSorted((a, b) => b - a)`,
	`[1,[2,[3]]].flat(2)`,
	`[1,[2,[3,[4]]]].flat(1.5)`,
	`[1,2].flatMap(n => [n, n])`,
	`[1,2,3].find(n => n > 1)`,
	`[1,2,3].findIndex(n => n > 5)`,
	`[1,2,3].indexOf(2)`,
	`[1,2,1].indexOf(1, 1)`,
	`[1,2,1].lastIndexOf(1, 1)`,
	`[1,2,1].lastIndexOf(1, undefined)`,
	`[1,2,3].includes(9)`,
	`[1,2,3].includes(1, 1)`,
	`[1,2,3].at(-1)`,
	`[1,2,3].join("|")`,
	`[null, undefined, 1].join("-")`,
	`[].join(",")`,
	`[1,2,3].some(n => n > 2)`,
	`[1,2,3].every(n => n > 0)`,
	`[...[1,2], ...[3]]`,
	`[..."abc"]`,
	`({ a: 1, ...{ b: 2 } })`,
	`({ ["a" + 1]: 2 })`,
	`Object.keys({ b: 1, a: 2 })`,
	`Object.keys({ ["__proto__"]: 1, a: 2 })`,
	`({ a: 1 })[\`a\`]`,
	`[3, 1, 2][\`toSorted\`]()`,
	`Object.keys([7, 8])`,
	`Object.values({ a: 1 })`,
	`Object.entries({ a: 1 })`,
	`Object.fromEntries([["a", 1], ["b", 2]])`,
	`Math.max(1, 2, 3)`,
	`Math.min()`,
	`Math.round(-2.5)`,
	`Math.abs(-3)`,
	`Math.trunc(-4.7)`,
	`Math.sign(-0)`,
	`JSON.stringify({ b: 1, a: [1, null] })`,
	`JSON.stringify("x")`,
	`JSON.stringify(Math)`,
	`JSON.stringify(Date)`,
	`JSON.stringify({ a: 1, b: { a: 2, c: 3 } }, ["a", "b"])`,
	`JSON.stringify([1, { a: 2 }], null, 2)`,
	`JSON.parse("[1,2]")`,
	`Number()`,
	`Number("")`,
	`Number("x")`,
	`Number(null)`,
	`Number(undefined)`,
	`String(null)`,
	`String([1,2])`,
	`String({})`,
	`Boolean("")`,
	`parseInt("12px")`,
	`parseFloat("3.5rem")`,
	`isNaN("x")`,
	`isFinite("3")`,
	`(255).toString(2)`,
	`(1.005).toFixed(2)`,
	`(12345.6789).toFixed(0)`,
	`"Hello".toLowerCase()`,
	`"ß".toUpperCase()`,
	`"Hello".slice(1, 3)`,
	`"Hello".substring(3, 1)`,
	`"Hello".at(-1)`,
	`"a-b-c".split("-")`,
	`"a-b-c".split("-", 2)`,
	`"a-b".split("-", 0)`,
	`"ab".split("")`,
	`"aaa".replace("a", "b")`,
	`"a".replace("a")`,
	`"abc".replace("b", "[$&$']")`,
	`"aaa".replaceAll("a", "b")`,
	`"aaa".replaceAll("", "-")`,
	`"x".repeat(3)`,
	`"x".repeat(NaN)`,
	`"x".repeat(-0.5)`,
	`"5".padStart(3, "0")`,
	`"abc".indexOf("c")`,
	`"abc".indexOf("a", 1)`,
	`"abcabc".lastIndexOf("a", 2)`,
	`"abc".includes("b")`,
	`"abc".includes("a", 1)`,
	`"abc".startsWith("ab")`,
	`"abc".startsWith("bc", 1)`,
	`" a ".trim().length`,
	`encodeURIComponent("a b&c")`,
	`decodeURIComponent("a%20b")`,
	`Array.from({ length: 3 })`,
	`Array.from({ length: -1 })`,
	`Array.from({ length: NaN })`,
	`Array.isArray("x")`,
	`[{ a: 1 }, { a: 2 }].map(({ a }) => a)`,
	`[[1, 2], [3, 4]].map(([x, y]) => x * y)`,
	`["abc"].map(([a, ...rest]) => rest)`,
	`[{ a: 1, b: 2 }].map(({ a, ...rest }) => rest)`,
	`[undefined].map((v = 5) => v)`,
	`[1,2,3].map((n, i, all) => n + i + all.length)`,
	`[1, 2].reduce((acc, v, i, all) => acc + v + i + all.length, 0)`,
	`[1].map((v, i, all, missing) => [v, missing])`,
	`[1].map((a, b, c, d, e = 5) => [a, e])`,
	`[{ a: 1 }].map(({ a }, i, [first] = [], d = 5) => [a, i, first, d])`,
	`[1,2,3][-1]`,
	`[1,2,3][1.5]`,
	`"abc"[-1]`,
	`"é".normalize("NFC").length`,
	`({ toString: 1 }).toString`,

	// Every remaining allow-listed method, one case each.
	`[1,2,3].reduceRight((a, b) => a + "" + b)`,
	`[1,2,3].reduceRight((a, b) => a + b, 10)`,
	`[1,2,3,2].findLast(n => n === 2)`,
	`[1,2,3,2].findLastIndex(n => n === 2)`,
	`[1,2,3,2].lastIndexOf(2)`,
	`"abc".endsWith("bc")`,
	`"abc".endsWith("b", 2)`,
	`"7".padEnd(3, "0")`,
	`"  a  ".trimStart()`,
	`"  a  ".trimEnd()`,
	`"a".localeCompare("b")`,
	`"a".localeCompare("B")`,
	`"a".localeCompare("B", "en", { sensitivity: "base" })`,
	`"ä".localeCompare("z", ["sv", "de"])`,
	`Date.UTC(2020, 0, 1)`,
	`Math.ceil(1.2)`,
	`Math.floor(1.8)`,
	`Math.sqrt(9)`,
	`Math.cbrt(27)`,
	`Math.pow(2, 10)`,
	`Math.hypot(3, 4)`,
	`Math.log(1)`,
	`Math.log2(8)`,
	`Math.log10(100)`,
	`Math.log1p(0)`,
	`Math.exp(0)`,
	`Math.expm1(0)`,
	`Math.sin(0)`,
	`Math.cos(0)`,
	`Math.tan(0)`,
	`Math.asin(0)`,
	`Math.acos(1)`,
	`Math.atan(0)`,
	`Math.atan2(0, 1)`,
	`Math.sinh(0)`,
	`Math.cosh(0)`,
	`Math.tanh(0)`,
	`Math.fround(1.5)`,
	`Math.clz32(1)`,
	`Math.imul(3, 4)`,
	`Number.isInteger(1.5)`,
	`Number.isFinite(1 / 0)`,
	`Number.isNaN(NaN)`,
	`Number.isSafeInteger(2 ** 53)`,
	`Number.parseInt("10", 2)`,
	`Number.parseFloat("1.5rem")`,
	`parseInt("ff", 16)`,
	`parseFloat("2.5x")`,

	`[1, 2, 3].toReversed()`,
	`[1, 2].concat([3, [4]], 5)`,
	`[1, 2, 3].toSpliced()`,
	`[1, 2, 3].toSpliced(1)`,
	`[1, 2, 3].toSpliced(1, undefined)`,
	`[1, 2, 3].toSpliced(-2, 1, "a", "b")`,
	`[1, 2, 3].toSpliced(9, 1, "z")`,
	`[1, 2, 3].with(-1, 9)`,
	`[1, 2, 3].with(0, 9)`,
	`"abc".charAt(1)`,
	`"abc".charAt(9)`,
	`"abc".charCodeAt(0)`,
	`"😀".codePointAt(0)`,
	`"a".concat(1, [2, 3], null)`,
	`"ok".isWellFormed()`,
	`"a\uD800b".isWellFormed()`,
	`"a\uD800b\uDC00\uD83D\uDE00".toWellFormed()`,
	`"İ".toLocaleLowerCase()`,
	`"i".toLocaleUpperCase()`,
	`"i".toLocaleUpperCase("tr")`,
	`"I".toLocaleLowerCase(["tr", "en"])`,
	`(123.456).toExponential(2)`,
	`(123.456).toPrecision(4)`,
	`(1).valueOf()`,
	`"a".valueOf()`,
	`Math.acosh(2)`,
	`Math.asinh(1)`,
	`Math.atanh(0.5)`,
	`Math.f16round(5.0005)`,
	`Math.f16round(65520)`,
	`Math.f16round(-1e-10)`,
	`Object.groupBy(scopes.root.products, p => p.category)`,
	`Object.groupBy([1, 2, 3], n => n % 2 ? "odd" : "even")`,
	`Object.groupBy(["a"], () => "__proto__")`,
	`Object.hasOwn({ a: 1 }, "a")`,
	`Object.hasOwn({ a: 1 }, "toString")`,
	`Object.is(-0, 0)`,
	`Object.is(NaN, NaN)`,
	`Array.of(7, 8)`,
	`String.fromCharCode(72, 105)`,
	`String.fromCodePoint(128512)`,
	`Date.parse("2020-01-02T03:04:05Z")`,
	`Date.parse("not a date")`,
	`Math.floor((Date.parse("2020-03-01T00:00:00Z") - Date.parse("2020-02-01T00:00:00Z")) / 86400000)`,
	`Date.UTC(2020, 11, 31, 23, 59, 59, 999)`,
	`Object.keys(Object.groupBy(["b", "a", "b"], t => t))`,
	`["b", "a", "b"].filter((t, i, all) => all.indexOf(t) === i)`,
	`(1234.5).toLocaleString()`,
	`[1234.5, 2].toLocaleString()`,
	`(1234.5).toLocaleString("de-DE")`,
	`(1234.5).toLocaleString(undefined, { style: "currency", currency: "USD" })`,
	`(0.256).toLocaleString("en-US", { style: "percent", maximumFractionDigits: 1 })`,
	`(1234567).toLocaleString("en-US", { notation: "compact" })`,
	`[1234.5, [2.5]].toLocaleString("en-US")`,
	`"abc".toLocaleString("de")`,
	`[1234.5, null, undefined, "x", true, [2.5, [3]]].toLocaleString()`,
	`[].toLocaleString()`,
	`["b", "a", "C"].toSorted((x, y) => x.localeCompare(y))`,
	`[0, 1, "", "a", null, undefined, NaN].filter(Boolean)`,
	`["1", "2.5", "", " 7 "].map(Number)`,
	`[1, null, undefined, true].map(String)`,
	`["1.5x", "x"].map(parseFloat)`,
	`[NaN, 1, "a"].filter(isNaN)`,
	`[Infinity, 1, "2"].filter(isFinite)`,
	`["a b", "é"].map(encodeURIComponent).map(decodeURIComponent)`,
	`[0, "", 3].some(Boolean) && [1, "x"].every(Boolean)`,
	`[0, "", 3].find(Boolean)`,
	`["1", "2"].flatMap(Number)`,
	`[5, 6].reduce(Number)`,
	`Object.groupBy([1, 2, 1], String)`,
	`["b", "a", "C"].toSorted((x, y) => x.localeCompare(y, "en", { caseFirst: "upper" }))`,
	`"abc".split(undefined, 0)`,
	`"a,b".split(",", 0)`,
	`"a-b-c".split("-", [2])`,
	`Array.from({})`,
	`Array.from({ length: 2, 0: "x" })`,
	`Object.hasOwn({ a: 1 }, ["a"])`,
	`Object.groupBy([1, 2, 3], x => [x % 2])`,
	`[5] - 1`,
	`[[5]] * 2`,
	`"3" * "4"`,
	`-"4"`,
	`[] + 1`,
	`[1, [2, 3]] + ""`,
	`[1, 2] == "1,2"`,
	`"10" < 9`,
	`Math.max([3], "7")`,
	`String([1, [2]])`,
	`[1, 2].join([";"])`,
	`[3, 1, undefined, 2, 10].toSorted()`,
	`[[2], [10], [1]].toSorted()`,
];
