// Shared by the language and parity suites so both back ends see the same list — a copy in each would drift.

export const SCOPES = {
	root: {
		q: "wid",
		count: 3,
		user: { name: "Ada", email: "ada@example.com", tags: ["a", "b"] },
		products: [
			{ id: 1, name: "Widget", sku: "W-1", category: "Tools", stock: 12, price: 9.5 },
			{ id: 2, name: "Gadget", sku: "G-2", category: "Tools", stock: 40, price: 24 },
			{ id: 3, name: "Doohickey", sku: "D-3", category: "Parts", stock: 0, price: 3.25 },
		],
		nothing: null,
	},
};

export const CORPUS = [
	`1 + 2 * 3 - 4 / 2`,
	`2 ** 3 ** 2`,
	`7 % 3`,
	`-0 === 0`,
	`0.1 + 0.2`,
	`1 / 0`,
	`-1 / 0`,
	`NaN === NaN`,
	`typeof undefined`,
	`typeof null`,
	`typeof 1`,
	`typeof "s"`,
	`typeof true`,
	`typeof []`,
	`typeof ({})`,
	`typeof Date`,
	`typeof Math`,
	`typeof (x => x)`,
	`"" + 1`,
	`1 + "1"`,
	`"3" * "4"`,
	`[] + 1`,
	`[1,2] + ""`,
	`null + 1`,
	`undefined === null`,
	`null == undefined`,
	`"" == 0`,
	`"0" == false`,
	`[] == false`,
	`1 < 2 === true`,
	`true && "a"`,
	`false && "a"`,
	`0 || "a"`,
	`"" ?? "a"`,
	`null ?? "a"`,
	`undefined ?? null ?? 3`,
	`(1 > 2) ? "y" : "n"`,
	`!!"x"`,
	`+"12"`,
	`-"12"`,
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`a${1}b${2}c`",
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	"`${null}|${undefined}|${0}`",
	`[1,2,3].map(n => n * 2)`,
	`[1,2,3].filter(n => n % 2 === 1)`,
	`[1,2,3].reduce((a, b) => a + b, 0)`,
	`[1,2,3].reduce((a, b) => a + b)`,
	`[3,1,2].toSorted()`,
	`[3,1,2].toSorted((a, b) => b - a)`,
	`[1,[2,[3]]].flat(2)`,
	`[1,2].flatMap(n => [n, n])`,
	`[1,2,3].find(n => n > 1)`,
	`[1,2,3].findIndex(n => n > 5)`,
	`[1,2,3].indexOf(2)`,
	`[1,2,1].indexOf(1, 1)`,
	`[1,2,1].lastIndexOf(1, 1)`,
	`[1,2,3].includes(9)`,
	`[1,2,3].includes(1, 1)`,
	`[1,2,3].at(-1)`,
	`[1,2,3].join("|")`,
	`[null, undefined, 1].join("-")`,
	`[].join(",")`,
	`[1,2,3].some(n => n > 2)`,
	`[1,2,3].every(n => n > 0)`,
	`[...[1,2], ...[3]]`,
	`[..."abc"]`,
	`({ a: 1, ...{ b: 2 } })`,
	`({ ["a" + 1]: 2 })`,
	`Object.keys({ b: 1, a: 2 })`,
	`Object.keys([7, 8])`,
	`Object.values({ a: 1 })`,
	`Object.entries({ a: 1 })`,
	`Object.fromEntries([["a", 1], ["b", 2]])`,
	`Math.max(1, 2, 3)`,
	`Math.min()`,
	`Math.round(-2.5)`,
	`Math.abs(-3)`,
	`Math.trunc(-4.7)`,
	`Math.sign(-0)`,
	`JSON.stringify({ b: 1, a: [1, null] })`,
	`JSON.stringify("x")`,
	`JSON.stringify(x => x)`,
	`JSON.stringify([x => x, { f: x => x }])`,
	`JSON.stringify(Math)`,
	`JSON.stringify(Date)`,
	`JSON.stringify({ a: 1, b: { a: 2, c: 3 } }, ["a", "b"])`,
	`JSON.stringify({ d: new Date(0), m: new Map(), u: new URL("https://x.example/") })`,
	`JSON.stringify([1, { a: 2 }], null, 2)`,
	`JSON.parse("[1,2]")`,
	`Number()`,
	`Number("")`,
	`Number("x")`,
	`Number(null)`,
	`Number(undefined)`,
	`String(null)`,
	`String([1,2])`,
	`String({})`,
	`Boolean("")`,
	`parseInt("12px")`,
	`parseFloat("3.5rem")`,
	`isNaN("x")`,
	`isFinite("3")`,
	`(255).toString(2)`,
	`(1.005).toFixed(2)`,
	`(12345.6789).toFixed(0)`,
	`"Hello".toLowerCase()`,
	`"ß".toUpperCase()`,
	`"Hello".slice(1, 3)`,
	`"Hello".substring(3, 1)`,
	`"Hello".at(-1)`,
	`"a-b-c".split("-")`,
	`"a-b-c".split("-", 2)`,
	`"a-b".split("-", 0)`,
	`"ab".split("")`,
	`"aaa".replace("a", "b")`,
	`"a".replace("a")`,
	`"abc".replace("b", "[$&$']")`,
	`"aaa".replaceAll("a", "b")`,
	`"aaa".replaceAll("", "-")`,
	`"x".repeat(3)`,
	`"5".padStart(3, "0")`,
	`"abc".indexOf("c")`,
	`"abc".indexOf("a", 1)`,
	`"abcabc".lastIndexOf("a", 2)`,
	`"abc".includes("b")`,
	`"abc".includes("a", 1)`,
	`"abc".startsWith("ab")`,
	`"abc".startsWith("bc", 1)`,
	`" a ".trim().length`,
	`encodeURIComponent("a b&c")`,
	`decodeURIComponent("a%20b")`,
	`new Date(0).toISOString()`,
	`new Date(0).getTime()`,
	`new Map([["a", 1]]).get("a")`,
	`new Set([1, 1]).size`,
	`new URL("https://x.example/a?b=1").pathname`,
	`Array.from({ length: 3 })`,
	`Array.from({ length: -1 })`,
	`Array.from({ length: NaN })`,
	`Array.isArray("x")`,
	`[{ a: 1 }, { a: 2 }].map(({ a }) => a)`,
	`[[1, 2], [3, 4]].map(([x, y]) => x * y)`,
	`["abc"].map(([a, ...rest]) => rest)`,
	`[{ a: 1, b: 2 }].map(({ a, ...rest }) => rest)`,
	`[undefined].map((v = 5) => v)`,
	`[1,2,3].map((n, i, all) => n + i + all.length)`,
	`[(a, b, c, d) => d].map(f => f(1, 2, 3, 4))`,
	`[(a, b, c, d, e) => [a, e]].map(f => f(1, 2, 3, 4, 5))`,
	`[(a, b, c, d, e) => e].map(f => f(1))`,
	`[({ a }, [b], c = 3, d, e = 5) => [a, b, c, e]].map(f => f({ a: 1 }, [2]))`,
	`[1,2,3][-1]`,
	`[1,2,3][1.5]`,
	`"abc"[-1]`,
	`"é".normalize("NFC").length`,
	`({ toString: 1 }).toString`,

	// Every remaining allow-listed method, one case each — a wrong result, a missing tick, or a leaked value would otherwise ship.
	`[1,2,3].forEach(n => n)`,
	`[1,2,3].reduceRight((a, b) => a + "" + b)`,
	`[1,2,3].reduceRight((a, b) => a + b, 10)`,
	`[1,2,3,2].findLast(n => n === 2)`,
	`[1,2,3,2].findLastIndex(n => n === 2)`,
	`[1,2,3,2].lastIndexOf(2)`,
	`"abc".endsWith("bc")`,
	`"abc".endsWith("b", 2)`,
	`"7".padEnd(3, "0")`,
	`"  a  ".trimStart()`,
	`"  a  ".trimEnd()`,
	`"a".localeCompare("b")`,
	`"a".localeCompare("B", "en", { sensitivity: "base" })`,
	`new Date(0).getMonth()`,
	`new Date(0).getDate()`,
	`new Date(0).getDay()`,
	`new Date(0).getHours()`,
	`new Date(0).getMinutes()`,
	`new Date(0).getSeconds()`,
	`new Date(0).getMilliseconds()`,
	`typeof new Date(0).getTimezoneOffset()`,
	`new Date(0).getUTCFullYear()`,
	`new Date(0).getUTCMonth()`,
	`new Date(0).getUTCDate()`,
	`new Date(0).getUTCDay()`,
	`new Date(0).getUTCHours()`,
	`new Date(0).getUTCMinutes()`,
	`new Date(0).getUTCSeconds()`,
	`new Date(0).valueOf()`,
	`new Date(0).toJSON()`,
	`new Date(0).toDateString()`,
	`new Date(0).toTimeString()`,
	`new Date(0).toLocaleDateString()`,
	`new Date(0).toLocaleTimeString()`,
	`Date.UTC(2020, 0, 1)`,
	`new Map([["a", 1]]).has("a")`,
	`new Map([["a", 1]]).size`,
	`new Set([1, 2]).has(2)`,
	`Math.ceil(1.2)`,
	`Math.floor(1.8)`,
	`Math.sqrt(9)`,
	`Math.cbrt(27)`,
	`Math.pow(2, 10)`,
	`Math.hypot(3, 4)`,
	`Math.log(1)`,
	`Math.log2(8)`,
	`Math.log10(100)`,
	`Math.log1p(0)`,
	`Math.exp(0)`,
	`Math.expm1(0)`,
	`Math.sin(0)`,
	`Math.cos(0)`,
	`Math.tan(0)`,
	`Math.asin(0)`,
	`Math.acos(1)`,
	`Math.atan(0)`,
	`Math.atan2(0, 1)`,
	`Math.sinh(0)`,
	`Math.cosh(0)`,
	`Math.tanh(0)`,
	`Math.fround(1.5)`,
	`Math.clz32(1)`,
	`Math.imul(3, 4)`,
	`Number.isInteger(1.5)`,
	`Number.isFinite(1 / 0)`,
	`Number.isNaN(NaN)`,
	`Number.isSafeInteger(2 ** 53)`,
	`Number.parseInt("10", 2)`,
	`Number.parseFloat("1.5rem")`,
	`parseInt("ff", 16)`,
	`parseFloat("2.5x")`,
	`[...new Set([1, 2])]`,
];
