// Workloads for prices.test.ts: each runs one operation many times, so its time per charged step shows.

const N = 2_000;
const WORDS = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta"];

const row = (i: number) => ({
	n: i * 1.37 + 0.5,
	i,
	s: `${WORDS[i % WORDS.length]} ${WORDS[(i * 3) % WORDS.length]} item-${i}`,
	d: new Date(Date.UTC(2020, i % 12, 1 + (i % 28), i % 24)),
	text: `2020-${String(1 + (i % 12)).padStart(2, "0")}-${String(1 + (i % 28)).padStart(2, "0")}T10:00:00Z`,
	a: Array.from({ length: 10 }, (_, j) => (i * 7 + j * 13) % 97),
	o: Object.fromEntries(Array.from({ length: 10 }, (_, j) => [`k${j}`, j])),
	set: new Set(Array.from({ length: 10 }, (_, j) => (i + j) % 20)),
	other: new Set(Array.from({ length: 10 }, (_, j) => (i + j * 2) % 20)),
	json: `{"id":${i},"name":"row ${i}","tags":["a","b"],"price":${i * 1.5}}`,
});

export const ROWS = Array.from({ length: N }, (_, i) => row(i));

const big = (n: number) => Array.from({ length: n }, (_, i) => (i * 7919) % 100_003);
const LONG = "lorem ipsum dolor sit amet ".repeat(4_000);

export const CONTEXT = {
	rows: ROWS,
	nums: big(20_000),
	strs: big(20_000).map(String),
	long: LONG,
	longJson: JSON.stringify(ROWS.map(({ n, i, s, json }) => ({ n, i, s, json }))),
	objs: ROWS.map(({ n, i, s }) => ({ n, i, s })),
	wide: Object.fromEntries(Array.from({ length: 300 }, (_, j) => [`key${j}`, j])),
	digits: "1".repeat(2_000),
	dateJunk: `2020-01-01${" ".repeat(2_000)}`,
	aaa: "a".repeat(20_000),
	needle: `${"a".repeat(200)}b`,
};

// Plain steps: member reads, arithmetic, comparisons, literals.
export const PLAIN: string[] = [
	`rows.map(r => r.n * 2 + r.i - (r.i > 3 ? 1 : 0))`,
	`rows.filter(r => r.i % 3 === 0 && r.n > 10).length`,
	`rows.map(r => ({ id: r.i, value: r.n, big: r.n > 100 }))`,
	`rows.reduce((acc, r) => acc + r.n * r.i, 0)`,
];

const each = (body: string) => `rows.map(r => ${body})`;

// One line per operation the language has. The key names the method, so coverage can be checked.
export const WORKLOADS: [string, string][] = [
	["map", each(`r.a.map(x => x + 1)`)],
	["filter", each(`r.a.filter(x => x > 40)`)],
	["reduce", each(`r.a.reduce((s, x) => s + x, 0)`)],
	["reduceRight", each(`r.a.reduceRight((s, x) => s + x, 0)`)],
	["find", each(`r.a.find(x => x > 90)`)],
	["findIndex", each(`r.a.findIndex(x => x > 90)`)],
	["findLast", each(`r.a.findLast(x => x > 90)`)],
	["findLastIndex", each(`r.a.findLastIndex(x => x > 90)`)],
	["some", each(`r.a.some(x => x > 90)`)],
	["every", each(`r.a.every(x => x > 2)`)],
	["slice", each(`r.a.slice(2, 8)`)],
	["concat", each(`r.a.concat(r.a, 1)`)],
	["join", each(`r.a.join("-")`)],
	["includes", each(`r.a.includes(50)`)],
	["indexOf", each(`r.a.indexOf(50)`)],
	["lastIndexOf", each(`r.a.lastIndexOf(50)`)],
	["at", each(`r.a.at(-1)`)],
	["flat", each(`[r.a, [r.a]].flat(2)`)],
	["flatMap", each(`r.a.flatMap(x => [x, x])`)],
	["toSorted", each(`r.a.toSorted()`)],
	["toSorted compare", each(`r.a.toSorted((x, y) => x - y)`)],
	["toReversed", each(`r.a.toReversed()`)],
	["toSpliced", each(`r.a.toSpliced(2, 3, 0)`)],
	["with", each(`r.a.with(3, 0)`)],
	["toString", each(`r.a.toString()`)],
	["toLocaleString", each(`r.a.toLocaleString()`)],
	["valueOf", each(`r.a.valueOf()`)],
	["at s", each(`r.s.at(3)`)],
	["charAt", each(`r.s.charAt(3)`)],
	["charCodeAt", each(`r.s.charCodeAt(3)`)],
	["codePointAt", each(`r.s.codePointAt(3)`)],
	["startsWith", each(`r.s.startsWith("beta")`)],
	["endsWith", each(`r.s.endsWith("7")`)],
	["includes s", each(`r.s.includes("gam")`)],
	["indexOf s", each(`r.s.indexOf("item")`)],
	["lastIndexOf s", each(`r.s.lastIndexOf("a")`)],
	["slice s", each(`r.s.slice(2, 9)`)],
	["substring", each(`r.s.substring(2, 9)`)],
	["concat s", each(`r.s.concat("-", r.i)`)],
	["split", each(`r.s.split(" ")`)],
	["replace", each(`r.s.replace("item", "row")`)],
	["replaceAll", each(`r.s.replaceAll("a", "A")`)],
	["repeat", each(`r.s.repeat(3)`)],
	["padStart", each(`r.s.padStart(40, "*")`)],
	["padEnd", each(`r.s.padEnd(40, "*")`)],
	["toLowerCase", each(`r.s.toLowerCase()`)],
	["toUpperCase", each(`r.s.toUpperCase()`)],
	["toLocaleLowerCase", each(`r.s.toLocaleLowerCase()`)],
	["toLocaleUpperCase", each(`r.s.toLocaleUpperCase()`)],
	["trim", each(`r.s.trim()`)],
	["trimStart", each(`r.s.trimStart()`)],
	["trimEnd", each(`r.s.trimEnd()`)],
	["normalize", each(`r.s.normalize("NFD")`)],
	["isWellFormed", each(`r.s.isWellFormed()`)],
	["toWellFormed", each(`r.s.toWellFormed()`)],
	["localeCompare", each(`r.s.localeCompare("delta")`)],
	["toString s", each(`r.s.toString()`)],
	["toLocaleString s", each(`r.s.toLocaleString()`)],
	["valueOf s", each(`r.s.valueOf()`)],
	["toFixed", each(`r.n.toFixed(2)`)],
	["toExponential", each(`r.n.toExponential(3)`)],
	["toPrecision", each(`r.n.toPrecision(4)`)],
	["toString n", each(`r.n.toString()`)],
	["toString radix", each(`r.i.toString(2)`)],
	["toLocaleString n", each(`r.n.toLocaleString()`)],
	["valueOf n", each(`r.n.valueOf()`)],
	...[
		"getTime", "getFullYear", "getMonth", "getDate", "getDay", "getHours", "getMinutes", "getSeconds",
		"getMilliseconds", "getTimezoneOffset", "getUTCFullYear", "getUTCMonth", "getUTCDate", "getUTCDay",
		"getUTCHours", "getUTCMinutes", "getUTCSeconds", "getUTCMilliseconds", "toISOString", "toJSON", "toUTCString",
		"toDateString", "toTimeString", "toString", "valueOf",
	].map((name): [string, string] => [`${name} d`, each(`r.d.${name}()`)]),
	["toLocaleDateString", each(`r.d.toLocaleDateString()`)],
	["toLocaleTimeString", each(`r.d.toLocaleTimeString()`)],
	["toLocaleString d", each(`r.d.toLocaleString()`)],
	["has set", each(`r.set.has(3)`)],
	["union", each(`r.set.union(r.other)`)],
	["intersection", each(`r.set.intersection(r.other)`)],
	["difference", each(`r.set.difference(r.other)`)],
	["symmetricDifference", each(`r.set.symmetricDifference(r.other)`)],
	["isSubsetOf", each(`r.set.isSubsetOf(r.other)`)],
	["isSupersetOf", each(`r.set.isSupersetOf(r.other)`)],
	["isDisjointFrom", each(`r.set.isDisjointFrom(r.other)`)],
	...[
		"abs", "ceil", "floor", "round", "trunc", "sign", "sqrt", "cbrt", "log", "log2", "log10", "log1p", "exp", "expm1",
		"sin", "cos", "tan", "asin", "acos", "atan", "sinh", "cosh", "tanh", "asinh", "acosh", "atanh", "fround",
		"f16round", "clz32",
	].map((name): [string, string] => [name, each(`Math.${name}(r.n / 3000)`)]),
	["acosh big", each(`Math.acosh(r.n + 1)`)],
	["pow", each(`Math.pow(r.n, 1.5)`)],
	["min", each(`Math.min(r.n, r.i, 3)`)],
	["max", each(`Math.max(r.n, r.i, 3)`)],
	["hypot", each(`Math.hypot(r.n, r.i)`)],
	["atan2", each(`Math.atan2(r.n, r.i)`)],
	["imul", each(`Math.imul(r.i, 3)`)],
	["random", each(`Math.random()`)],
	["sumPrecise", each(`Math.sumPrecise(r.a)`)],
	["parse", each(`JSON.parse(r.json)`)],
	["stringify", each(`JSON.stringify(r.o)`)],
	["keys o", each(`Object.keys(r.o)`)],
	["values o", each(`Object.values(r.o)`)],
	["entries o", each(`Object.entries(r.o)`)],
	["fromEntries", each(`Object.fromEntries([["a", r.i], ["b", r.n]])`)],
	["groupBy", each(`Object.groupBy(r.a, x => x % 3)`)],
	["hasOwn", each(`Object.hasOwn(r.o, "k3")`)],
	["is", each(`Object.is(r.n, r.i)`)],
	["isArray", each(`Array.isArray(r.a)`)],
	["from", each(`Array.from(r.a, x => x * 2)`)],
	["of", each(`Array.of(r.i, r.n)`)],
	["isInteger", each(`Number.isInteger(r.n)`)],
	["isFinite", each(`Number.isFinite(r.n)`)],
	["isNaN", each(`Number.isNaN(r.n)`)],
	["isSafeInteger", each(`Number.isSafeInteger(r.i)`)],
	["parseFloat", each(`Number.parseFloat(r.s)`)],
	["parseInt", each(`Number.parseInt(r.s, 10)`)],
	["fromCharCode", each(`String.fromCharCode(72, r.i % 100 + 20)`)],
	["fromCodePoint", each(`String.fromCodePoint(128512, r.i % 100 + 20)`)],
	["now", each(`Date.now()`)],
	["parse date", each(`Date.parse(r.text)`)],
	["UTC", each(`Date.UTC(2020, r.i % 12, 1)`)],
	["Number()", each(`Number(r.s)`)],
	["String()", each(`String(r.n)`)],
	["Boolean()", each(`Boolean(r.i)`)],
	["parseInt()", each(`parseInt(r.text)`)],
	["parseFloat()", each(`parseFloat(r.text)`)],
	["isNaN()", each(`isNaN(r.s)`)],
	["isFinite()", each(`isFinite(r.n)`)],
	["encodeURIComponent", each(`encodeURIComponent(r.s)`)],
	["decodeURIComponent", each(`decodeURIComponent(r.s)`)],
	["new Date()", each(`new Date(r.n)`)],
	["new Date(text)", each(`new Date(r.text)`)],
	["new Date(parts)", each(`new Date(2020, r.i % 12, 1, 10)`)],
	["new Set", each(`new Set(r.a)`)],
	["string +", each(`r.s + " / " + r.i`)],
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	["template", each("`${r.s} (${r.i})`")],
	["object spread", each(`({ ...r.o, extra: 1 })`)],
	["array spread", each(`[...r.a, 1]`)],
	["destructure", `rows.map(({ n, i, s }) => n + i + s.length)`],
	["optional chain", each(`r.o?.k3 ?? r.o?.missing?.x`)],
	["typeof", each(`typeof r.s === "string"`)],
	// Size: one operation over a large input
	["join large", `strs.join(",")`],
	["split large", `long.split(" ")`],
	["repeat large", `long.repeat(3).length`],
	["replaceAll large", `long.replaceAll("o", "0").length`],
	["includes large", `long.includes("zzz")`],
	["indexOf large", `long.indexOf("zzz")`],
	["lastIndexOf large", `long.lastIndexOf("zzz")`],
	["normalize large", `long.normalize("NFD").length`],
	["isWellFormed large", `long.isWellFormed()`],
	["toWellFormed large", `long.toWellFormed().length`],
	["toLowerCase large", `long.toUpperCase().toLowerCase().length`],
	["parse large", `JSON.parse(longJson).length`],
	["stringify large", `JSON.stringify(objs).length`],
	["toSorted large", `nums.toSorted().length`],
	["toSorted strings large", `strs.toSorted().length`],
	["toSorted compare large", `nums.toSorted((a, b) => a - b).length`],
	["includes array large", `nums.includes(-1)`],
	["indexOf array large", `nums.indexOf(-1)`],
	["slice large", `nums.slice(1).length`],
	["concat large", `nums.concat(nums).length`],
	["flat large", `[nums, nums].flat().length`],
	["new Set large", `new Set(nums).size`],
	["union large", `new Set(nums).union(new Set(strs)).size`],
	["sumPrecise large", `Math.sumPrecise(nums)`],
	["spread wide", `rows.map(r => ({ ...wide, i: r.i }))`],
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	["template large", "`${long}|${long}`.length"],
	["string + large", `(long + long).length`],
	// Conversions the engine runs in time of the input: a long string parses, an array joins
	["parse text -", each(`digits - 1`)],
	["parse text <", each(`digits < 5`)],
	["parse text ==", each(`digits == 5`)],
	["parse text unary", each(`+digits`)],
	["parse text Number()", each(`Number(digits)`)],
	["parse text at", each(`r.a.at(digits)`)],
	["join by +", each(`r.a + ""`)],
	// biome-ignore lint/suspicious/noTemplateCurlyInString: the string IS the expression under test
	["join by template", each("`${r.a}`")],
	["join by String()", each(`String(r.a)`)],
	["join by Math", each(`Math.max(r.a)`)],
	["join by includes", each(`r.s.includes(r.a)`)],
	["parse date text", each(`Date.parse(dateJunk)`)],
	["new Date(long text)", each(`new Date(dateJunk)`)],
	["toSorted arrays", `rows.map(r => r.a).toSorted().length`],
	["lastIndexOf worst", `aaa.lastIndexOf(needle)`],
	["from length large", `Array.from({ length: 20000 }).length`],
];
