"use client";

import { Info } from "lucide-react";
import { type MouseEvent, useState } from "react";
import { cn } from "@/lib/utils";

const BUBBLE_WIDTH = 288;
const MARGIN = 16;
const GAP = 6;

const formatTokens = (n: number) => (n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n));

export type Usage = { inputTokens: number; outputTokens: number; costUsd: number | null; model: string | null };

export function UsageLine({ inputTokens, outputTokens, costUsd, model, className }: Usage & { className?: string }) {
  return (
    <p className={cn("flex items-center gap-1.5 text-xs text-muted-foreground", className)}>
      <span>
        {formatTokens(inputTokens)} in · {formatTokens(outputTokens)} out
        {typeof costUsd === "number" ? ` · ≈$${costUsd.toFixed(3)}` : ""}
      </span>
      <CostInfo model={model} />
    </p>
  );
}

// position:fixed and clamped to the viewport, so it fits wherever the icon sits.
function CostInfo({ model }: { model: string | null }) {
  const [pos, setPos] = useState<{ left: number; top: number; width: number } | null>(null);
  const toggle = (event: MouseEvent<HTMLButtonElement>) => {
    if (pos) return setPos(null);
    const rect = event.currentTarget.getBoundingClientRect();
    const width = Math.min(BUBBLE_WIDTH, window.innerWidth - MARGIN * 2);
    setPos({
      left: Math.min(Math.max(MARGIN, rect.left), window.innerWidth - width - MARGIN),
      top: rect.bottom + GAP,
      width,
    });
  };
  return (
    <span className="relative inline-flex align-middle">
      <button
        type="button"
        aria-label="About this cost"
        className="inline-flex items-center text-muted-foreground hover:text-foreground"
        onClick={toggle}
        onBlur={() => setPos(null)}
      >
        <Info className="size-3.5" />
      </button>
      {pos && (
        <span
          style={pos}
          className="fixed z-50 rounded-md border bg-popover px-3 py-2 text-left text-xs text-popover-foreground shadow-md"
        >
          {model && (
            <>
              Generated by <code className="break-all">{model}</code>.{" "}
            </>
          )}
          Cost is what OpenRouter reported charging for the run.
        </span>
      )}
    </span>
  );
}
