// Generated by vovk-cli v0.3.0-beta.0 at 2026-08-27T18:25:56.594Z
import type { VovkFetcher } from 'vovk/fetcher';
import { createRPC } from 'vovk/create-rpc';
import { schema } from './schema';

import type { Controllers as Controllers0 } from "../app/api/[[...vovk]]/route.ts";



export const ConnectionController = createRPC<Controllers0["ConnectionController"], typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'ConnectionController', import('vovk/fetcher'),
  { validateOnClient: undefined,  }
);

export const ToolController = createRPC<Controllers0["ToolController"], typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'ToolController', import('vovk/fetcher'),
  { validateOnClient: undefined,  }
);

export const ChatController = createRPC<Controllers0["ChatController"], typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'ChatController', import('vovk/fetcher'),
  { validateOnClient: undefined,  }
);

export const GenerationController = createRPC<Controllers0["GenerationController"], typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'GenerationController', import('vovk/fetcher'),
  { validateOnClient: undefined,  }
);

export { schema };
